version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_usuario
    environment:
      POSTGRES_DB: usuarios_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: estrela
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  rabbitmq:
 #   image: rabbitmq:3-management
  #  container_name: rabbitmq_usuario
   # ports:
    #  - "5672:5672"
     # - "15672:15672"
    #environment:
     # RABBITMQ_DEFAULT_USER: guest
      #RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
